services:
  postgres_customer:
    container_name: postgres_customer
    image: postgres
    environment:
      POSTGRES_USER: mado
      POSTGRES_PASSWORD: password
      POSTGRES_DB: customer
    volumes:
      - postgres_customer:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres_customer
    restart: unless-stopped

  redis_fraud:
    container_name: redis_fraud
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_fraud:/data
    networks:
      - redis_fraud
    restart: unless-stopped

  mongo_notification:
    container_name: mongo_notification
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: notification
    volumes:
      - mongo_notification:/data/db
    ports:
      - "27017:27017"
    networks:
      - mongo_notification
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres_customer
    restart: unless-stopped

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redis_insight
    ports:
      - "5540:5540"
    networks:
      - redis_fraud
    restart: always

  mongo-express:
    image: mongo-express
    ports:
      - "8000:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo_notification:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - mongo_notification
    restart: unless-stopped


  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - spring

  apigw:
    build: ./apigw
    container_name: apigw
    ports:
    - "8083:8083"
    environment:
      - spring.cloud.gateway.routes[0].id=customer
      - spring.cloud.gateway.routes[0].uri=http://customer:8080
      - spring.cloud.gateway.routes[0].predicates[0]=Path=/customer/**

      - spring.cloud.gateway.routes[1].id=fraud
      - spring.cloud.gateway.routes[1].uri=http://fraud:8081
      - spring.cloud.gateway.routes[1].predicates[0]=Path=/fraud/**

      - spring.cloud.gateway.routes[2].id=notification
      - spring.cloud.gateway.routes[2].uri=http://notification:8082
      - spring.cloud.gateway.routes[2].predicates[0]=Path=/notification/**
    networks:
      - spring
    restart: unless-stopped

  customer:
    build: ./customer
    container_name: customer
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:postgresql://postgres_customer:5432/customer
      - spring.rabbitmq.addresses=rabbitmq:5672
      - clients.fraud.url=http://fraud:8081
    networks:
      - spring
      - postgres_customer
    depends_on:
      - postgres_customer
      - rabbitmq


  fraud:
    build: ./fraud
    container_name: fraud
    ports:
      - "8081:8080"
    environment:
      - spring.data.redis.host=redis_fraud
      - spring.data.redis.port=6379
    networks:
      - redis_fraud
      - spring
    depends_on:
      - redis_fraud

  notification:
    build: ./notification
    container_name: notification
    ports:
      - "8082:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://root:example@mongo_notification:27017/notification?authSource=admin
      - SPRING_DATA_MONGODB_DATABASE=notification
      - spring.rabbitmq.addresses=rabbitmq:5672
    networks:
      - spring
      - mongo_notification
    depends_on:
      - mongo_notification
      - rabbitmq

networks:
  postgres_customer:
    driver: bridge
  redis_fraud:
    driver: bridge
  mongo_notification:
    driver: bridge
  spring:
    driver: bridge

volumes:
  postgres_customer:
  redis_fraud:
  mongo_notification:
  pgadmin:
